#!/bin/bash
rm -rf .git
git init
git add --all
git commit -m "initial"

heroku create -s cedar -b https://github.com/ddollar/heroku-buildpack-multi.git

git push heroku master

# fix up path (See https://github.com/ddollar/heroku-buildpack-multi/issues/5 for details)
heroku config:set PATH=/app/vendor/R/bin:bin:vendor/bundle/ruby/1.9.1/bin:/usr/local/bin:/usr/bin:/bin

heroku logs
