#!/bin/bash

set -e

rversion="$1"

if [ -z "$rversion" ]; then
  echo "USAGE: $0 VERSION"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
vendordir=/app/vendor
prefix=$vendordir/R

# download dependancies 
curl http://gfortran.com/download/x86_64/snapshots/gcc-4.3.tar.xz -o gcc-4.3.tar.xz
curl http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/glibc_2.7.orig.tar.gz -o glibc_2.7.tar.gz

# download R sources and unpack
curl http://cran.r-project.org/src/base/R-2/R-$rversion.tar.gz -o R-$rversion.tar.gz
tar xzf R-$rversion.tar.gz

# create output directories
mkdir -p $vendordir
mkdir -p $prefix

# unpack dependancies (into vendor)
cd $vendordir
tar xJf $basedir/gcc-4.3.tar.xz
tar xzf $basedir/glibc_2.7.tar.gz && tar xjf glibc-2.7/glibc-2.7.tar.bz2

# R needs to know where gfortran and glibc header files are
export PATH=$vendordir/gcc-4.3/bin:$PATH
export LDFLAGS="-L$vendordir/gcc-4.3/lib64/ -R$vendordir/gcc-4.3/lib64/"
export CPPFLAGS="-I$vendordir/glibc-2.7/string/ -I$vendordir/glibc-2.7/time"

# configure and make R
cd $basedir/R-$rversion/
./configure --prefix=$prefix --without-x && make && make install
