#!/bin/bash

#
# use this script to build the R binaries on a vagrant instance
#

# fail fast
set -e

# debug
# set -x

if [[ ! -f .env ]]; then
  cp .env.example .env
  echo "Please edit the .env file and supply your AWS credentials before continuing."
  exit 1
fi

r_version="${1:-3.1.0}"
build_no="${2:-`date +%Y%m%d-%H%M`}"

# provision vagrant instance & build R binaries
R_VERSION=$r_version BUILD_NO=$build_no vagrant up

# destroy the vagrant instance (comment out if debugging build is required)
# vagrant destroy --force

# NOTE: build outputs will be in the current directory
