#!/bin/bash

# This script is executed by the shell provisioner of Vagrant

# fail fast
set -e

# debug
# set -x

r_version="${1:-3.1.0}"
build_no="${2:-`date +%Y%m%d-%H%M`}"

# create output directory
sudo mkdir -p /app
sudo chown vagrant /app
sudo chgrp vagrant /app

# build R binaries
cd /vagrant
./build-r $r_version $build_no &> ./build-r-$build_no.log
