# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  # Heroku Celadon Cedar
  #  https://github.com/ejholmes/vagrant-heroku
  config.vm.box_url = "http://dl.dropbox.com/u/1906634/heroku.box"
  config.vm.box = "heroku"

  config.vm.provision :shell, :path => "vagrant-install"

end
