# -*- mode: ruby -*-
# vi: set ft=ruby :

DEFAULT_R_VERSION = "3.1.0"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Heroku Celadon Cedar
  #  https://github.com/ejholmes/vagrant-heroku
  config.vm.box = "heroku"
  config.vm.box_url = "https://dl.dropboxusercontent.com/s/rnc0p8zl91borei/heroku.box"

  config.vm.provision :shell, :path => './vagrant-build' do |shell|
    shell.privileged = false

    # pass the R version and Build No along...
    shell.args = "#{ENV['R_VERSION'] || DEFAULT_R_VERSION} #{ENV['BUILD_NO'] || Time.now.strftime('%Y%m%d-%H%M')}"
  end

end
