#!/bin/bash

rversion=2.15.1

tar czf build.tgz build-r

vulcan build --source=./build.tgz \
             --prefix=/app/vendor \
             --command="./build-r $rversion" \
             --verbose

rm build.tgz
