#!/bin/bash
rm -rf .git
git init
git add --all
git commit -m "initial"

heroku create -s cedar -b https://github.com/virtualstaticvoid/heroku-buildpack-r.git

app=`heroku apps:info -s | grep ^name=`
app=${app:5}

git push heroku master

# start rserve process
heroku ps:scale rserve=1

# check
heroku logs --app $app
