#!/bin/bash
rm -rf .git
git init
git add --all
git commit -m "initial"

heroku create --stack cedar-14 --buildpack https://github.com/virtualstaticvoid/heroku-buildpack-r.git#cedar-14

app=`heroku apps:info -s | grep ^name=`
app=${app:5}

git push heroku master

# run R console
heroku run "R --no-save -e 'demo(nlm)'" --app $app

echo Run "heroku apps:destroy $app --confirm $app" to clean up
