#!/bin/bash
rm -rf .git
git init
git add --all
git commit -m "initial"

heroku create -s cedar -b https://github.com/ddollar/heroku-buildpack-multi.git

app=`heroku apps:info -s | grep ^git-url=`
app=${app:23:-4}

git push heroku master

# check...
heroku logs --app $app
