#!/bin/bash

shopt -s extglob
set -e

dir=`mktemp -d`
cp -r . $dir
pushd $dir

git init
git add --all
git commit -m "initial"

heroku create --stack cedar-14 --buildpack https://github.com/virtualstaticvoid/heroku-buildpack-r.git#cedar-14

app=`heroku apps:info -s | grep ^name=`
app=${app:5}

git push heroku master

# run R console
heroku run "R --no-save -e 'capabilities()'" --app $app

popd

# clean up
heroku apps:destroy $app --confirm $app
rm -rf $dir
