#!/bin/bash
rm -rf .git
git init
git add --all
git commit -m "initial"

heroku create -s cedar -b https://github.com/virtualstaticvoid/heroku-buildpack-r.git#gsl2

app=`heroku apps:info -s | grep ^git-url=`
app=${app:23:-4}

git push heroku master

# run R console
heroku run "R --no-save" --app $app
