#!/bin/bash

shopt -s extglob
set -e

branch=${1:-heroku-16}
destroy=${2:-1}
repo=${3:-github.com/virtualstaticvoid}


# create a temporary directory and copy
# the test application to it
dir=$(mktemp -d)
cp -r . $dir
pushd $dir

# commit to git for push to heroku
git init
echo "*.log" > .gitignore
git add --all
git commit -m "initial"

# create the app with R buildpack
heroku create --stack heroku-16 \
              --buildpack https://$repo/heroku-buildpack-r.git#$branch

# trick to get the app name
app=$(heroku apps:info -j | jq -r '.app.name')

git push heroku master

# run R console
heroku run R --no-save -f /app/prog.R --app $app

popd

# destroy the app, and clean up temporary files
if [[ "$destroy" -eq "1" ]]; then

  # clean up
  heroku apps:destroy $app --confirm $app
  rm -rf $dir

else

  GREEN='\033[1;32m'
  RESET='\033[0m'
  echo -e "${GREEN} ********************************************************************************"
  echo -e ""
  echo -e " Run the following command to destroy the test application when you are done."
  echo -e ""
  echo -e "  heroku apps:destroy $app"
  echo -e ""
  echo -e "********************************************************************************"
  echo -e "${RESET}"

fi
